apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  labels:
    app: go-web-app
spec:
  ports:
    - port: 80
      targetPort: 9090  # Corrected to 'targetPort' instead of 'targetport'
      protocol: TCP
  selector:
    app: go-web-app
  type: ClusterIP

